import 'qxo_api_service.dart';
import 'qxo_pricing_service.dart';
import 'bom_calculator.dart';

/// Submits a BOM as a quote to QXO/Beacon using resolved item numbers.
class QxoQuoteService {
  final _api = QxoApiService();

  /// Submit the BOM items as a Beacon quote.
  /// Uses pre-resolved pricing data to map BOM names → QXO item numbers.
  Future<Map<String, dynamic>> submitQuote({
    required String projectName,
    required BomResult bom,
    required Map<String, QxoPricedItem> pricedItems,
    String? address,
    String? city,
    String? state,
    String? postalCode,
  }) async {
    final quoteItems = <QxoQuoteItem>[];

    for (final item in bom.activeItems) {
      final priced = pricedItems[item.name];
      if (priced == null) continue; // skip items we couldn't resolve

      quoteItems.add(QxoQuoteItem(
        itemNumber: priced.qxoItemNumber,
        quantity: item.orderQty.toInt(),
        uom: priced.uom ?? _mapUnit(item.unit),
        displayName: item.name,
      ));
    }

    if (quoteItems.isEmpty) {
      throw Exception(
          'No BOM items could be matched to QXO catalog. Fetch pricing first.');
    }

    return _api.submitQuote(
      quoteName: projectName,
      items: quoteItems,
      address1: address,
      city: city,
      state: state,
      postalCode: postalCode,
      quoteNotes: 'Generated by ProTPO Estimator',
    );
  }

  /// Map ProTPO unit names to QXO UOM codes.
  String _mapUnit(String unit) {
    switch (unit.toLowerCase()) {
      case 'rolls':
        return 'RL';
      case 'boards':
      case 'sheets':
        return 'PC';
      case 'bundles':
        return 'BDL';
      case 'boxes':
        return 'BX';
      case 'each':
        return 'EA';
      case 'lf':
        return 'LF';
      case 'gal':
      case 'gallons':
        return 'GL';
      case 'tubes':
        return 'EA';
      case 'ctn':
        return 'CTN';
      default:
        return 'EA';
    }
  }
}
