// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPtwL5EA6-90IcjElbKNR-T4uK1poD6BA',
    appId: '1:331847071461:web:793bbf28b05ea30aeb460c',
    messagingSenderId: '331847071461',
    projectId: 'tpo-pro-245d1',
    authDomain: 'tpo-pro-245d1.firebaseapp.com',
    storageBucket: 'tpo-pro-245d1.firebasestorage.app',
    measurementId: 'G-5HZGF053R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDssHLN8dI0i5kNPedZcHSfcIxbwyYrqx0',
    appId: '1:331847071461:android:9b6e600c2e43c812eb460c',
    messagingSenderId: '331847071461',
    projectId: 'tpo-pro-245d1',
    storageBucket: 'tpo-pro-245d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB65ITyeK8UEOLE9mfMraQdO1MyxHjYNy4',
    appId: '1:331847071461:ios:13376fdbf49b0f8beb460c',
    messagingSenderId: '331847071461',
    projectId: 'tpo-pro-245d1',
    storageBucket: 'tpo-pro-245d1.firebasestorage.app',
    iosBundleId: 'com.example.protpoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB65ITyeK8UEOLE9mfMraQdO1MyxHjYNy4',
    appId: '1:331847071461:ios:13376fdbf49b0f8beb460c',
    messagingSenderId: '331847071461',
    projectId: 'tpo-pro-245d1',
    storageBucket: 'tpo-pro-245d1.firebasestorage.app',
    iosBundleId: 'com.example.protpoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfBf5ysf0CEBCk8K1TgHiM0NwWe28QCiI',
    appId: '1:331847071461:web:ee7e83881c8e8809eb460c',
    messagingSenderId: '331847071461',
    projectId: 'tpo-pro-245d1',
    authDomain: 'tpo-pro-245d1.firebaseapp.com',
    storageBucket: 'tpo-pro-245d1.firebasestorage.app',
    measurementId: 'G-129F2TSXYT',
  );
}
